package io.riskscanner.base.mapper;

import io.riskscanner.base.domain.MsgChannel;
import io.riskscanner.base.domain.MsgChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    long countByExample(MsgChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int deleteByExample(MsgChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int deleteByPrimaryKey(Long msgChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int insert(MsgChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int insertSelective(MsgChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    List<MsgChannel> selectByExample(MsgChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    MsgChannel selectByPrimaryKey(Long msgChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByExampleSelective(@Param("record") MsgChannel record, @Param("example") MsgChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByExample(@Param("record") MsgChannel record, @Param("example") MsgChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByPrimaryKeySelective(MsgChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByPrimaryKey(MsgChannel record);
}