package io.riskscanner.base.mapper;

import io.riskscanner.base.domain.Msg;
import io.riskscanner.base.domain.MsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    long countByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int deleteByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int deleteByPrimaryKey(Long msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int insert(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int insertSelective(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    List<Msg> selectByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    Msg selectByPrimaryKey(Long msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByExampleSelective(@Param("record") Msg record, @Param("example") MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByExample(@Param("record") Msg record, @Param("example") MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByPrimaryKeySelective(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByPrimaryKey(Msg record);
}