package io.riskscanner.base.mapper;

import io.riskscanner.base.domain.MsgSetting;
import io.riskscanner.base.domain.MsgSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    long countByExample(MsgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int deleteByExample(MsgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int deleteByPrimaryKey(Long msgSettingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int insert(MsgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int insertSelective(MsgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    List<MsgSetting> selectByExample(MsgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    MsgSetting selectByPrimaryKey(Long msgSettingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByExampleSelective(@Param("record") MsgSetting record, @Param("example") MsgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByExample(@Param("record") MsgSetting record, @Param("example") MsgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByPrimaryKeySelective(MsgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    int updateByPrimaryKey(MsgSetting record);
}