package io.riskscanner.base.mapper;

import io.riskscanner.base.domain.Proxy;
import io.riskscanner.base.domain.ProxyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProxyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    long countByExample(ProxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    int deleteByExample(ProxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    int insert(Proxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    int insertSelective(Proxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    List<Proxy> selectByExample(ProxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    Proxy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") Proxy record, @Param("example") ProxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    int updateByExample(@Param("record") Proxy record, @Param("example") ProxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    int updateByPrimaryKeySelective(Proxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Tue Apr 06 14:08:13 CST 2021
     */
    int updateByPrimaryKey(Proxy record);
}