package io.riskscanner.base.mapper;

import io.riskscanner.base.domain.ResourceItem;
import io.riskscanner.base.domain.ResourceItemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourceItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    long countByExample(ResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int deleteByExample(ResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int insert(ResourceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int insertSelective(ResourceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    List<ResourceItem> selectByExampleWithBLOBs(ResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    List<ResourceItem> selectByExample(ResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    ResourceItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByExampleSelective(@Param("record") ResourceItem record, @Param("example") ResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ResourceItem record, @Param("example") ResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByExample(@Param("record") ResourceItem record, @Param("example") ResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByPrimaryKeySelective(ResourceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ResourceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByPrimaryKey(ResourceItem record);
}