package io.riskscanner.base.mapper;

import io.riskscanner.base.domain.ScanHistory;
import io.riskscanner.base.domain.ScanHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScanHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    long countByExample(ScanHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int deleteByExample(ScanHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int insert(ScanHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int insertSelective(ScanHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    List<ScanHistory> selectByExample(ScanHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    ScanHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByExampleSelective(@Param("record") ScanHistory record, @Param("example") ScanHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByExample(@Param("record") ScanHistory record, @Param("example") ScanHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByPrimaryKeySelective(ScanHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_history
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    int updateByPrimaryKey(ScanHistory record);
}