
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜识别与信息和信息处理设施的资产，编制并维护这些资产的清单。', '资产清单', '识别组织资产，并定义适当的保护职责。', '1）识别相关的信息处理设施的资产，并进行分类，分类可包括：硬件资产、软件资产和数据资产等；（购买实例）2）建立信息资产清单，可以形成文件化记录或以配置库形式管理，并实时保持更新。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('清单中所维护的资产宜分配所有权。', '资产所有权', '识别组织资产，并定义适当的保护职责。', '1）识别相关的信息处理设施的资产，并进行分类，分类可包括：硬件资产、软件资产和数据资产等；（购买实例）2）建立信息资产清单，可以形成文件化记录或以配置库形式管理，并实时保持更新。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('信息宜按照法律要求、价值、关键性以及它对未授权泄露或修改的敏感性予以分级。', '信息的分级', '确保信息按照其对组织的重要性受到适当级别的保护。', '1）建立信息分级的管理要求，分级方案应包含分级规则和分级评审的准则，宜命名每个不同的级别以便于分级方案的使用；2）信息资产的责任主体宜对其分级负责。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜按照组织所采纳的信息分类机制建立和实施一组合适的信息标记规程。', '信息的标记', '确保信息按照其对组织的重要性受到适当级别的保护。', '按照信息分级的管理要求，对公司的信息进行了分级标记，分级的结果宜体现资产的价值，该价值取决于资产对组织的敏感性和重要性，分级结果应根据资产在其生命周期中的价值、敏感性和重要性的变化进行更新。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('用户宜仅能访问已获专门授权使用的网络和网络服务。', '网络和网络服务的访问', '限制对信息和信息处理设施的访问。', '按网络和网络服务的要求配置公司的网络安全策略。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜实施正式的用户注册及注销规程，使访问权限得以分配。', '用户注册及注销', '确保授权用户访问系统和服务，并防止未授权的访问。', '信息系统提供注册、注销、冻结用户账号的功能；系统可保证用户ID唯一性，使得用户与其行为链接起来。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜实施正式的用户访问开通过程，以分配或撤销所有系统和服务所有用户类型的访问权限。', '用户访问开通', '确保授权用户访问系统和服务，并防止未授权的访问。', '信息系统被授权用户的访问级别与访问策略匹配；授权规程完成之后，访问权限才被激活。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜限制和控制特殊访问权限的分配及使用。', '特殊访问权限管理', '确保授权用户访问系统和服务，并防止未授权的访问。', '管理者进行了特权用户授权，并记录特殊访问权限用户名单；定期评审特殊授权用户与其工作职责的匹配性。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜通过正式的管理过程控制秘密鉴别信息的分配。', '用户秘密鉴别信息管理', '确保授权用户访问系统和服务，并防止未授权的访问。', '秘密鉴别信息（如：密码、动态口令、云计算AK等）分配时应考虑其安全性，包括：验证用户身份；系统支持用户初始密码强制修改功能；系统支持以安全的方式将临时秘密鉴别信息提供给用户，避免通过外部方或未受保护的（明文）电子邮件提供。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('资产所有者宜定期复查用户的访问权限。', '用户访问权限的复查', '确保授权用户访问系统和服务，并防止未授权的访问。', '定期进行各信息系统的访问权复查，权限分配应适宜；定期（加严）核查特殊权限的分配。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('所有雇员、外部方人员对信息和信息处理设施的访问权限宜在任用、合同或协议终止时撤销，或在变化时调整。', '撤销或调整访问权限', '确保授权用户访问系统和服务，并防止未授权的访问。', '调整已变更岗位用户的访问权限，并立即删除或禁用已离开组织的用户的访问权限。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜依照访问控制策略限制对信息和应用系统功能的访问。', '信息访问限制', '防止对系统和应用的未授权访问。', '各信息和信息系统的管理员对用户访问特定信息的授权过程。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('在访问控制策略要求下，访问操作系统和应用宜通过安全登录规程加以控制。', '安全登录规程', '防止对系统和应用的未授权访问。', '用户鉴别的强度应和所访问信息的级别相适应，登录信息系统的应选择适当的身份鉴别技术（口令/密码、双因素认证、动态口令）以证实用户身份。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('口令管理系统宜是交互式的，并宜确保优质的口令。', '口令管理系统', '防止对系统和应用的未授权访问。', '设置的访问密码强度，应满足访问控制策略中对密码管理的要求。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('对于可能超越系统和应用程序控制措施的适用工具软件的使用宜加以限制并严格控制。', '特殊权限实用工具软件的使用', '防止对系统和应用的未授权访问。', '按照访问控制策略的要求对特殊权限实用工具软件的安装、使用进行管控。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜开发和实施使用密码控制措施来保护信息的策略。', '使用密码控制的策略', '恰当和有效的利用密码学保护信息的保密性、真实性或完整性。', '建立加密管理要求，在软件开发和日常管理过程中，使用了基本的加密策略，如数据传输加密、敏感信息脱敏、匿名化等。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜开发和实施贯穿整个密钥生命周期的关于密钥使用、保护和生存期的策略。', '密钥管理', '恰当和有效的利用密码学保护信息的保密性、真实性或完整性。', '建立加密管理要求，具有密钥生成、存储、归档、恢复、分发、卸任和损坏的安全过程；用来生成、存储和归档密钥的设备应进行物理保护。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('资源的使用宜加以监视、调整，并作出对于未来容量要求的预测，以确保拥有所需的系统性能。', '容量管理', '确保正确、安全的操作信息处理设施。', '根据相关业务系统关键性，来识别容量需求，使用监控系统来监视系统资源的使用情况，并对未来容量需求进行规划和趋势分析。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜实施恶意软件的检测、预防和恢复的控制措施，以及适当的提高用户安全意识。', '控制恶意软件', '确保对信息和信息处理设施进行恶意软件防护。', '服务器、终端电脑应安装、使用杀毒软件，并设置查杀策略，病毒库应定期更新。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜按照已设的备份策略，定期备份和测试信息、软件及系统镜像。', '信息备份', '为了防止数据丢失。', '制定重要数据的备份策略，数据备份执行情况应与备份策略一直；应定期进行备份恢复测试。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜产生记录用户活动、异常情况、故障和信息安全事态的事态日志，并保持定期评审。', '事态记录', '记录事态和生成证据。', '应记录认证范围涉及的关键信息系统的日志以及网络设备的日志，并定期评审。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('记录日志的设施和日志信息宜加以保护，以防止篡改和未授权的访问。', '日志信息的保护', '记录事态和生成证据。', '信息系统日志用户自定义保存（依据行业监管要求保存）网络安全日志信息应至少保存6个月；应实施控制措施以防止日志信息的未授权更改和日志设施的运行问题，包括：a) 已记录的消息类型的更改；b) 日志文件被编辑或被删除；c) 超过日志文件存储介质的容量，导致不能记录事态或过去记录事态被写覆盖。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('系统管理员和系统操作员的活动宜记入日志，保护日志并定期评审。', '管理员和操作员日志', '记录事态和生成证据。', '应记录、保护和评审系统管理员和系统操作员的操作日志，以保持特权用户的可核查性。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜及时得到现用信息系统技术脆弱性的信息，评价组织对这些脆弱性的暴露程度，并采取适当的措施来处理相关的风险。', '技术脆弱性的控制', '防止技术脆弱性被利用。', '应定义和建立与技术脆弱性管理相关的角色和职责；定期对信息系统实施漏洞扫描，并对扫描结果进行跟踪处置对操作系统和网络设备更新并安装补丁，应评估与安装该补丁相关的风险。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('涉及对运行系统验证的审计要求和活动，宜谨慎地加以规划并取得批准，以便使造成业务过程中断最小化。', '信息系统审计控制措施', '将运行系统审计活动的影响最小化。', '策划和实施信息系统审计时，信息系统审计过程和使用工具应是安全可靠的，并对审计活动和审计使用工具进行评审和批准。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜管理和控制网络，以保护系统中信息和应用程序的安全。', '网络控制', '确保网络中信息的安全性并保护支持性信息处理设施。', '实施控制措施以确保网络上信息的安全、保护相互连接的服务免遭未授权访问。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('安全机制、服务级别以及所有网络服务的管理要求宜予以确定并包括在所有网络服务协议中，无论这些服务是由内部提供的还是外包的。', '网络服务安全', '确保网络中信息的安全性并保护支持性信息处理设施。', '网络服务提供商（如：网络运营商、网络设备提供商）应在其服务协议中服务级别要求以及信息安全要求。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('宜在网络中隔离信息服务、用户及信息系统。', '网络隔离', '确保网络中信息的安全性并保护支持性信息处理设施。', '网络分成独立的网络域。域的选择可以基于信任级别（如公共访问域、桌面域、服务器域）、组织单元（如人力资源、财务、市场）或组合（如连接到多个组织单元的服务器域）。域之间的隔离可以使用不同的物理网络或者使用不同的逻辑网络（如虚拟专用网络）。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('信息安全事态宜被评估，并且确定是否划分成信息安全事件。', '评估和确定信息安全事态', '确保采用一致和有效的方法对信息安全事件进行管理，包括安全事件和弱点的传达。', '根据信息安全事件管理规范对信息安全事态评估和确认的记录。');
INSERT INTO `rule_inspection_report` (`project`, `item_sort_first_level`, `item_sort_second_level`, `improvement`) VALUES ('信息处理设备宜冗余部署，以满足高可用性需求。', '信息处理设施的可用性', '确保信息处理设施的有效性。', '组织应识别信息系统可用性的业务要求。当使用现有系统架构不能保证可用性时，应考虑冗余组件或架构。如可能，应测试冗余信息系统以确保从一个组件到另一个组件的故障切换按预期执行。');

INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('159e19e9-e956-4c52-92fc-c9746372e448', '77');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('17dbe1a1-e9e7-4513-aa07-597ae932ff73', '10');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('17dbe1a1-e9e7-4513-aa07-597ae932ff73', '123');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('ca991f61-49a4-49b2-9d14-16ca338d8149', '124');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('68363ad8-cce8-4458-b8f1-9bd1d1af54a7', '83');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('bf9a87c9-f709-4f84-8a86-5afde3eb40c3', '107');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('f7b906de-63e0-479b-b766-2e50df8fbe19', '117');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('63dedb65-0237-4402-8a5c-1d2137840fdd', '100');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('b8e09c5a-fecc-4400-b831-d7f75f9cee01', '102');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('1aab5692-85a5-4151-b67c-8c2c93353916', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('5f6c1aed-8c46-48e6-b48d-2cf06568831f', '107');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('311daee9-3c15-4b19-8fb7-97823c57eb23', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('6359bdcd-0d1d-4e43-817c-cc338f07a065', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('ccf64ae6-7f99-40fe-b45f-d86a4b63bdcc', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('ab3306d0-e734-4977-a462-42de0e1cf263', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('5c4d5e15-ce0a-4322-8406-47e8bcb10bf4', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('6bbd42bc-a251-498a-8b19-8de8c55e32aa', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('f50705c1-8930-4a53-b32d-da08eda1161c', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('3808ac89-6fb0-4953-a6f3-a464f1b603bd', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('49fb8964-15ab-45b9-864c-69b7e7cd5b71', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('5227e5cd-7e66-4f32-8515-7895fdc79535', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('6bc48581-98bb-4563-9735-a505002e344f', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('fc94e69d-a3bb-46a4-9f24-60f8369c6f15', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('cfc3ad75-2599-47ab-bfb2-af8a07531250', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('afd0480e-651b-4229-aa68-d642e074fb59', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('ffecf574-f388-40ad-aebb-9a46ef798dcf', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('ae7de16c-0a39-4119-a5c0-d0916f549e95', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('332ce586-70de-4053-a922-f76d6340a03c', '48');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('33a70278-c772-4ef0-93c9-4b9d3df1e242', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('108c875b-bf3c-4034-b07d-15faa8715257', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('7557ce1b-aacf-4cd7-bb19-6e411621daf3', '46');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('9312ca46-1ce9-4e42-86b2-7f9b5c0db090', '46');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('6a71a114-ba92-4e0b-bd9d-2f6c8ecee88d', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('f6c72297-33db-49dd-a106-06cf2ff47069', '18');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('3e324555-83e2-4ac9-8ac2-1dae350d52ff', '18');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('6967e834-ace6-48d2-9f95-f541b614810d', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('c3259122-ac07-4256-83da-b6361c9d3abb', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('94d168d0-8e62-4173-96fd-326eb267273e', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('c95fde94-53a5-4658-98a4-56a0c6d951d4', '97');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('d690be79-2e8c-4054-bbe6-496bd29e91fe', '97');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('beda16d0-93fd-4366-9ebf-f5ce1360cd60', '97');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('8c635fda-7f89-4d5c-b0f4-2116f1b65554', '80');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('fdef013f-ce14-468a-9af4-1c0fabc7e6e1', '80');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('6fd132c0-b4df-4685-b132-5441d1aef2f8', '18');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('b1491f69-f3b8-40ae-9659-4242dbc30a0b', '97');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('0be7f5d4-766c-4b2b-910d-bec0f3aac977', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('07eb95ef-6d78-4b9a-8555-a42b6a16de99', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('5c47228c-7fe1-484b-a5b6-7c1968074f69', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('b57cbdba-b4d7-4da7-84db-25b9f2d5324b', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('bd1a0479-ef54-4208-a520-50caf6acfe87', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('fa5e89e3-417d-4296-9d17-ca51ed914be5', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('befc89d7-1811-404a-9226-f8ecc22820e0', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('fa60960a-0e38-4502-9834-1ab1277e9aaa', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('350a097a-dfeb-4fd0-a3af-49049da5c025', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('6bb291bd-fcdf-4aa9-8fdf-69e761c9c4e0', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('1fbd8c76-90e7-48e4-8281-ef597bb484e8', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('0dc8ae24-71f8-449a-8834-d59f8fbdf991', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('ee74d071-d39e-4b0e-b4a3-e7ad24fbce12', '123');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('8ad73e84-141a-40c4-bd56-1813535e8e92', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('e86583b9-12dd-4316-980a-5eeeba86f9ca', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('f38d83c9-c4b9-47b8-8135-f9bdf96cf8ec', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('1ab302fb-1b06-410a-b17a-fdf7843d6182', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('c1375dfe-c0b1-4e53-9c2b-6a0f29258a08', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('0d6270fc-3744-42cd-a850-65ac0b8ef514', '123');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('9929cc2a-7a9b-4643-a813-0e4359b09eb0', '119');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('0d51321e-e26c-4147-b730-5b1403384487', '122');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('9b1d1a9c-6c7e-44db-a15c-c0c82b1040eb', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('a944a483-c23f-4d62-bdd8-d2a20a4aaeca', '125');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('0a5a7796-6b53-408a-ba49-7fd9e51d82f4', '28');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('72af2230-8555-4e0c-a06a-721436a0644e', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('4a64e90e-92ea-4d5a-a753-3c5ca92a2b95', '100');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('197e41e7-cbc3-4eef-b5ad-5153c9232449', '97');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('7c37887f-0b8d-444c-bad7-e43cd2b41578', '124');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('10754933-241e-42db-bb3c-42e13cb40b0f', '113');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('39c87069-a3c6-4ab3-9974-f844a89872b5', '98');
INSERT INTO rule_inspection_report_mapping (`rule_id`, `report_id`) VALUES ('ebc80d1e-5dd9-4b86-8037-fb7c9727084a', '90');
