package io.riskscanner.base.domain;

import java.io.Serializable;

public class MessageTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.type
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.event
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.user_id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.task_type
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.webhook
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String webhook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.identification
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String identification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.is_set
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private Boolean isSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.resource_id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.create_time
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_task.template
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private String template;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_task
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.id
     *
     * @return the value of message_task.id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.id
     *
     * @param id the value for message_task.id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.type
     *
     * @return the value of message_task.type
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.type
     *
     * @param type the value for message_task.type
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.event
     *
     * @return the value of message_task.event
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.event
     *
     * @param event the value for message_task.event
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.user_id
     *
     * @return the value of message_task.user_id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.user_id
     *
     * @param userId the value for message_task.user_id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.task_type
     *
     * @return the value of message_task.task_type
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.task_type
     *
     * @param taskType the value for message_task.task_type
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.webhook
     *
     * @return the value of message_task.webhook
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getWebhook() {
        return webhook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.webhook
     *
     * @param webhook the value for message_task.webhook
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setWebhook(String webhook) {
        this.webhook = webhook == null ? null : webhook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.identification
     *
     * @return the value of message_task.identification
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.identification
     *
     * @param identification the value for message_task.identification
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setIdentification(String identification) {
        this.identification = identification == null ? null : identification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.is_set
     *
     * @return the value of message_task.is_set
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public Boolean getIsSet() {
        return isSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.is_set
     *
     * @param isSet the value for message_task.is_set
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setIsSet(Boolean isSet) {
        this.isSet = isSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.resource_id
     *
     * @return the value of message_task.resource_id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.resource_id
     *
     * @param resourceId the value for message_task.resource_id
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.create_time
     *
     * @return the value of message_task.create_time
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.create_time
     *
     * @param createTime the value for message_task.create_time
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_task.template
     *
     * @return the value of message_task.template
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_task.template
     *
     * @param template the value for message_task.template
     *
     * @mbg.generated Mon Mar 08 15:05:52 CST 2021
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }
}