package io.riskscanner.base.domain;

import java.io.Serializable;

public class Msg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.msg_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Long msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.user_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.type_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.status
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.param
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.create_time
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.read_time
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Long readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.content
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.msg_id
     *
     * @return the value of msg.msg_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.msg_id
     *
     * @param msgId the value for msg.msg_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.user_id
     *
     * @return the value of msg.user_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.user_id
     *
     * @param userId the value for msg.user_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.type_id
     *
     * @return the value of msg.type_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.type_id
     *
     * @param typeId the value for msg.type_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.status
     *
     * @return the value of msg.status
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.status
     *
     * @param status the value for msg.status
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.param
     *
     * @return the value of msg.param
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.param
     *
     * @param param the value for msg.param
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.create_time
     *
     * @return the value of msg.create_time
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.create_time
     *
     * @param createTime the value for msg.create_time
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.read_time
     *
     * @return the value of msg.read_time
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Long getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.read_time
     *
     * @param readTime the value for msg.read_time
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setReadTime(Long readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.content
     *
     * @return the value of msg.content
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.content
     *
     * @param content the value for msg.content
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}