package io.riskscanner.base.domain;

import java.util.ArrayList;
import java.util.List;

public class MsgChannelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public MsgChannelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMsgChannelIdIsNull() {
            addCriterion("msg_channel_id is null");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdIsNotNull() {
            addCriterion("msg_channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdEqualTo(Long value) {
            addCriterion("msg_channel_id =", value, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdNotEqualTo(Long value) {
            addCriterion("msg_channel_id <>", value, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdGreaterThan(Long value) {
            addCriterion("msg_channel_id >", value, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("msg_channel_id >=", value, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdLessThan(Long value) {
            addCriterion("msg_channel_id <", value, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdLessThanOrEqualTo(Long value) {
            addCriterion("msg_channel_id <=", value, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdIn(List<Long> values) {
            addCriterion("msg_channel_id in", values, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdNotIn(List<Long> values) {
            addCriterion("msg_channel_id not in", values, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdBetween(Long value1, Long value2) {
            addCriterion("msg_channel_id between", value1, value2, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andMsgChannelIdNotBetween(Long value1, Long value2) {
            addCriterion("msg_channel_id not between", value1, value2, "msgChannelId");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("channel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("channel_name =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("channel_name <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("channel_name >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("channel_name <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("channel_name <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("channel_name like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("channel_name not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("channel_name in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("channel_name not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("channel_name between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("channel_name not between", value1, value2, "channelName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_channel
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 26 18:58:34 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_channel
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}