package io.riskscanner.base.domain;

import java.io.Serializable;

public class MsgSetting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_setting.msg_setting_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Long msgSettingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_setting.user_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_setting.type_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_setting.channel_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Long channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_setting.enable
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_setting
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_setting.msg_setting_id
     *
     * @return the value of msg_setting.msg_setting_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Long getMsgSettingId() {
        return msgSettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_setting.msg_setting_id
     *
     * @param msgSettingId the value for msg_setting.msg_setting_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setMsgSettingId(Long msgSettingId) {
        this.msgSettingId = msgSettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_setting.user_id
     *
     * @return the value of msg_setting.user_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_setting.user_id
     *
     * @param userId the value for msg_setting.user_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_setting.type_id
     *
     * @return the value of msg_setting.type_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_setting.type_id
     *
     * @param typeId the value for msg_setting.type_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_setting.channel_id
     *
     * @return the value of msg_setting.channel_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_setting.channel_id
     *
     * @param channelId the value for msg_setting.channel_id
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_setting.enable
     *
     * @return the value of msg_setting.enable
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_setting.enable
     *
     * @param enable the value for msg_setting.enable
     *
     * @mbg.generated Thu Aug 26 18:58:34 CST 2021
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public Boolean match(MsgSetting setting) {
        return setting.getTypeId() == typeId && setting.getChannelId() == channelId;
    }
}
