package io.riskscanner.base.domain;

import java.io.Serializable;

public class ResourceItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.resource_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.f2c_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String f2cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.resource_type
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.plugin_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String pluginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.plugin_name
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String pluginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.plugin_icon
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String pluginIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.account_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.region_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.region_name
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.severity
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String severity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.create_time
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.update_time
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_item.resource
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.id
     *
     * @return the value of resource_item.id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.id
     *
     * @param id the value for resource_item.id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.resource_id
     *
     * @return the value of resource_item.resource_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.resource_id
     *
     * @param resourceId the value for resource_item.resource_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.f2c_id
     *
     * @return the value of resource_item.f2c_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getF2cId() {
        return f2cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.f2c_id
     *
     * @param f2cId the value for resource_item.f2c_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setF2cId(String f2cId) {
        this.f2cId = f2cId == null ? null : f2cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.resource_type
     *
     * @return the value of resource_item.resource_type
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.resource_type
     *
     * @param resourceType the value for resource_item.resource_type
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.plugin_id
     *
     * @return the value of resource_item.plugin_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getPluginId() {
        return pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.plugin_id
     *
     * @param pluginId the value for resource_item.plugin_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setPluginId(String pluginId) {
        this.pluginId = pluginId == null ? null : pluginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.plugin_name
     *
     * @return the value of resource_item.plugin_name
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getPluginName() {
        return pluginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.plugin_name
     *
     * @param pluginName the value for resource_item.plugin_name
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName == null ? null : pluginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.plugin_icon
     *
     * @return the value of resource_item.plugin_icon
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getPluginIcon() {
        return pluginIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.plugin_icon
     *
     * @param pluginIcon the value for resource_item.plugin_icon
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setPluginIcon(String pluginIcon) {
        this.pluginIcon = pluginIcon == null ? null : pluginIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.account_id
     *
     * @return the value of resource_item.account_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.account_id
     *
     * @param accountId the value for resource_item.account_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.region_id
     *
     * @return the value of resource_item.region_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.region_id
     *
     * @param regionId the value for resource_item.region_id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.region_name
     *
     * @return the value of resource_item.region_name
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.region_name
     *
     * @param regionName the value for resource_item.region_name
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.severity
     *
     * @return the value of resource_item.severity
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.severity
     *
     * @param severity the value for resource_item.severity
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setSeverity(String severity) {
        this.severity = severity == null ? null : severity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.create_time
     *
     * @return the value of resource_item.create_time
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.create_time
     *
     * @param createTime the value for resource_item.create_time
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.update_time
     *
     * @return the value of resource_item.update_time
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.update_time
     *
     * @param updateTime the value for resource_item.update_time
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_item.resource
     *
     * @return the value of resource_item.resource
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_item.resource
     *
     * @param resource the value for resource_item.resource
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2021
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }
}